# Generated by Django 5.0.6 on 2024-08-20 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('current_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('public', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Engineering', 'Engineering'), ('Mathematics', 'Mathematics'), ('History', 'History'), ('Literature', 'Literature'), ('Languages', 'Languages'), ('Arts', 'Arts'), ('Health and Medicine', 'Health & Medicine'), ('Programming', 'Programming'), ('Lifeskills', 'Lifeskills/Self Help'), ('CLEP', 'CLEP Exams'), ('Misc', 'Misc.')], default='Misc', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 8, 20, 6, 17, 24, 888196, tzinfo=datetime.timezone.utc))),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32)),
                ('image', models.ImageField(upload_to='flashcards_web_imgs')),
            ],
        ),
    ]
