# Generated by Django 5.0.6 on 2024-08-24 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 24, 21, 5, 7, 594742, tzinfo=datetime.timezone.utc)),
        ),
    ]
