# Generated by Django 5.0.6 on 2024-08-25 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 8, 49, 3, 810528, tzinfo=datetime.timezone.utc)),
        ),
    ]
