# Generated by Django 5.0.6 on 2024-08-20 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 20, 6, 25, 41, 788909, tzinfo=datetime.timezone.utc)),
        ),
    ]
